version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
      - ./migrations:/usr/src/app/migrations
      - ./config:/usr/src/app/config
      - ./test:/usr/src/app/test
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./tsconfig.build.json:/usr/src/app/tsconfig.build.json
      - ./nest-cli.json:/usr/src/app/nest-cli.json
      - ./eslint.config.mjs:/usr/src/app/eslint.config.mjs
    command: [ "npm", "run", "start:dev" ]
    ports:
      - '${APP_PORT:-3000}:3000'
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:-admin}
      MYSQL_DATABASE: ${DATABASE_NAME:-db2-db}
      MYSQL_USER: ${DATABASE_USER:-admin}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-admin}
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
